apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspmvclogging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aspmvclogging
    spec:
      containers:
      - name: aspmvclogging
        image: andregomesbr/aspmvclogging:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
        app: aspmvclogging